Metrics/AbcSize:
  Max: 20
Lint/AmbiguousBlockAssociation:
  Enabled: false
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
  Include:
    - 'app/**/*'
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/*'
