Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
  Include:
    - 'app/**/*'
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
