require: rubocop-rails
Metrics/AbcSize:
  Max: 20
  Exclude:
    # Constrained by gem expectations
    - 'app/models/breadcrumb_trail.rb'
Lint/AmbiguousBlockAssociation:
  Enabled: false
Rails/FindEach:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
  Include:
    - 'app/**/*'
Metrics/MethodLength:
  ExcludedMethods: ['role_permissions']
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
Metrics/BlockLength:
  Exclude:
    # BL config too long
    - 'app/controllers/catalog_controller.rb'
    - 'spec/**/*'
    - 'lib/tasks/*'
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
Rails/DynamicFindBy:
  Whitelist:
    - find_by_alternate_identifier
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Style/MissingRespondToMissing:
  Enabled: false
