# Use postgres/example user/password credentials
version: '3.7'
services:
  db:
    volumes:
      - /home/circleci/db:/var/lib/postgresql/data/pgdata
  web:
    build: /home/circleci/charon
    volumes:
      - /home/circleci/charon:/charon
  solr:
    volumes:
    - solr:/opt/solr/server/solr/mycores
    - /home/circleci/charon/solr:/solr_config
