# Use postgres/example user/password credentials
version: '3.7'
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: example
  web:
    image: nakatomi/charon_web
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/charon
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db:
  web:
