# Use postgres/example user/password credentials
version: '3.7'
volumes:
  solr:
  db:
  web:
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: example
  web:
    image: nakatomi/charon_web
    build: .
    command: /bin/sh -c "rm -f /charon/tmp/pids/server.pid && bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rake db:migrate RAILS_ENV=test && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/charon
    ports:
      - "3000:3000"
    depends_on:
      - db
      - solr
  solr:
    image: solr:7.2-alpine
    ports:
    - 8983:8983
    volumes:
    - solr:/opt/solr/server/solr/mycores
    - ./solr:/solr_config
    entrypoint:
    - bash
    - "-c"
    - "precreate-core blacklight-core; precreate-core blacklight-core-test; exec solr -f"
    healthcheck:
      test:
      - CMD
      - wget
      - "-O"
      - "/dev/null"
      - http://localhost:8983/solr/
      interval: 30s
      timeout: 5s
      retries: 3


# solr:
#   image: solr
#   ports:
#     - "8983:8983"
#   volumes:
#     - solr:/opt/solr/server/solr/blacklight-core
