# Use postgres/example user/password credentials
version: '3.7'
volumes:
  solr:
  db:
  web:
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: example
  web:
    image: nakatomi/charon_web
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/charon
    ports:
      - "3000:3000"
    depends_on:
      - db
      - solr
  solr:
    image: solr:7.2-alpine
    ports:
    - 8983:8983
    volumes:
    - solr:/opt/solr/server/solr/mycores
    - ./solr:/solr_config
    entrypoint:
    - docker-entrypoint.sh
    - solr-precreate
    - blacklight-core
    - blacklight-core-test
    - "/solr_config/config"
    healthcheck:
      test:
      - CMD
      - wget
      - "-O"
      - "/dev/null"
      - http://localhost:8983/solr/
      interval: 30s
      timeout: 5s
      retries: 3


# solr:
#   image: solr
#   ports:
#     - "8983:8983"
#   volumes:
#     - solr:/opt/solr/server/solr/blacklight-core
