# Use postgres/example user/password credentials
version: '3.7'
services:
  sidekiq:
    build: .
    volumes:
      - ./:/home/charon/web
      - storage:/home/charon/storage
  web:
    build: .
    volumes:
      - ./:/home/charon/web
      - storage:/home/charon/storage
