# Use postgres/example user/password credentials
version: '3.7'
volumes:
  solr:
  db:
  images:
  storage:
  redis:
services:
  sidekiq:
    image: nakatomi/charon_web:latest
    command: bundle exec sidekiq
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/0
  redis:
    image: redis:6-alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  web:
    image: nakatomi/charon_web
    ports:
      - 3000:3000
    entrypoint: /home/charon/web/docker-entrypoint.sh
  solr:
    image: nakatomi/charon_solr
    ports:
    - 8983:8983
    volumes:
    - solr:/opt/solr/server/solr/mycores/blacklight-core/data
    healthcheck:
      test:
      - CMD
      - wget
      - "-O"
      - "/dev/null"
      - http://localhost:8983/solr/
      interval: 30s
      timeout: 5s
      retries: 3
  iiif:
    image: nakatomi/charon_cantaloupe:4.0
    ports:
      - 8182:8182
    volumes:
      - images:/imageroot
