version: 2
jobs:
  build:
    working_directory: ~/charon
    docker:
      - image: circleci/ruby:2.5-node-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update -qq
            sudo apt-get install -y apt-utils build-essential libpq-dev
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - ~/caches/charon.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i ~/caches/charon.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=nakatomi/charon_web:latest -t nakatomi/charon_web .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p ~/caches
            docker save -o ~/caches/charon.tar charon
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/caches/charon.tar
      - run:
          name: Start container
          command: |
            set -x
            docker-compose up -d
      - run:
          name: Verify container is working
          command: |
            docker-compose exec web \
              curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:3000
