version: 2
jobs:
  build:
    machine: true
    working_directory: ~/charon
    docker:
      - image: circleci/ruby:2.5-node-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update -qq
            sudo apt-get install -y apt-utils build-essential libpq-dev
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - ~/caches/charon.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i ~/caches/charon.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=nakatomi/charon_web:latest -t nakatomi/charon_web .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p ~/caches
            docker save -o ~/caches/charon.tar nakatomi/charon_web
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/caches/charon.tar
      - run:
          name: Start container
          command: |
            set -x
            docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3000 -timeout 1m
      - run:
          name: Verify container is working
          command: |
            docker-compose exec web \
              curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:3000
