default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: example
  pool: 5

development:
  <<: *default
  database: charon_development

staging:
  <<: *default
  database: charon_staging

test:
  <<: *default
  database: charon_test
