development:
  url: 'http://localhost:8182/iiif'
staging:
  url: 'http://charon.library.northeastern.edu/iiif'
test: &test
  url: 'http://localhost:8182/iiif'
production:
  url: 'http://charon.library.northeastern.edu/iiif'
